/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthSystemUserRouteImport } from './routes/_auth.system.user'
import { Route as AuthSystemRoleRouteImport } from './routes/_auth.system.role'
import { Route as AuthSystemQueuesRouteImport } from './routes/_auth.system.queues'
import { Route as AuthSystemMenuRouteImport } from './routes/_auth.system.menu'
import { Route as AuthSystemLogRouteImport } from './routes/_auth.system.log'
import { Route as AuthSystemDictRouteImport } from './routes/_auth.system.dict'
import { Route as AuthSystemConfigRouteImport } from './routes/_auth.system.config'
import { Route as AuthMallMemberRouteImport } from './routes/_auth.mall.member'
import { Route as AuthCmsTagRouteImport } from './routes/_auth.cms.tag'
import { Route as AuthCmsResourceRouteImport } from './routes/_auth.cms.resource'
import { Route as AuthCmsCommentRouteImport } from './routes/_auth.cms.comment'
import { Route as AuthCmsCategoryRouteImport } from './routes/_auth.cms.category'
import { Route as AuthCmsArticleRouteImport } from './routes/_auth.cms.article'
import { Route as AuthMallShippingTemplateIndexRouteImport } from './routes/_auth.mall.shipping-template.index'
import { Route as AuthMallProductIndexRouteImport } from './routes/_auth.mall.product.index'
import { Route as AuthMallOrderIndexRouteImport } from './routes/_auth.mall.order.index'
import { Route as AuthMallCouponIndexRouteImport } from './routes/_auth.mall.coupon.index'
import { Route as AuthMallCollectionIndexRouteImport } from './routes/_auth.mall.collection.index'
import { Route as AuthMallCategoryIndexRouteImport } from './routes/_auth.mall.category.index'
import { Route as AuthMallAfterSaleIndexRouteImport } from './routes/_auth.mall.after-sale.index'
import { Route as AuthMallShippingTemplateCreateRouteImport } from './routes/_auth.mall.shipping-template.create'
import { Route as AuthMallProductCreateRouteImport } from './routes/_auth.mall.product.create'
import { Route as AuthMallOrderIdRouteImport } from './routes/_auth.mall.order.$id'
import { Route as AuthMallCouponCreateRouteImport } from './routes/_auth.mall.coupon.create'
import { Route as AuthMallCollectionCreateRouteImport } from './routes/_auth.mall.collection.create'
import { Route as AuthMallAfterSaleIdRouteImport } from './routes/_auth.mall.after-sale.$id'
import { Route as AuthMallShippingTemplateEditIdRouteImport } from './routes/_auth.mall.shipping-template.edit.$id'
import { Route as AuthMallProductEditIdRouteImport } from './routes/_auth.mall.product.edit.$id'
import { Route as AuthMallCouponEditIdRouteImport } from './routes/_auth.mall.coupon.edit.$id'
import { Route as AuthMallCollectionEditIdRouteImport } from './routes/_auth.mall.collection.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_auth.lazy').then((d) => d.Route))
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.index.lazy').then((d) => d.Route))
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.dashboard.lazy').then((d) => d.Route),
)
const AuthSystemUserRoute = AuthSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.user.lazy').then((d) => d.Route),
)
const AuthSystemRoleRoute = AuthSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.role.lazy').then((d) => d.Route),
)
const AuthSystemQueuesRoute = AuthSystemQueuesRouteImport.update({
  id: '/system/queues',
  path: '/system/queues',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemMenuRoute = AuthSystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.menu.lazy').then((d) => d.Route),
)
const AuthSystemLogRoute = AuthSystemLogRouteImport.update({
  id: '/system/log',
  path: '/system/log',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.log.lazy').then((d) => d.Route),
)
const AuthSystemDictRoute = AuthSystemDictRouteImport.update({
  id: '/system/dict',
  path: '/system/dict',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.dict.lazy').then((d) => d.Route),
)
const AuthSystemConfigRoute = AuthSystemConfigRouteImport.update({
  id: '/system/config',
  path: '/system/config',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.config.lazy').then((d) => d.Route),
)
const AuthMallMemberRoute = AuthMallMemberRouteImport.update({
  id: '/mall/member',
  path: '/mall/member',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.member.lazy').then((d) => d.Route),
)
const AuthCmsTagRoute = AuthCmsTagRouteImport.update({
  id: '/cms/tag',
  path: '/cms/tag',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.cms.tag.lazy').then((d) => d.Route))
const AuthCmsResourceRoute = AuthCmsResourceRouteImport.update({
  id: '/cms/resource',
  path: '/cms/resource',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.cms.resource.lazy').then((d) => d.Route),
)
const AuthCmsCommentRoute = AuthCmsCommentRouteImport.update({
  id: '/cms/comment',
  path: '/cms/comment',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.cms.comment.lazy').then((d) => d.Route),
)
const AuthCmsCategoryRoute = AuthCmsCategoryRouteImport.update({
  id: '/cms/category',
  path: '/cms/category',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.cms.category.lazy').then((d) => d.Route),
)
const AuthCmsArticleRoute = AuthCmsArticleRouteImport.update({
  id: '/cms/article',
  path: '/cms/article',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.cms.article.lazy').then((d) => d.Route),
)
const AuthMallShippingTemplateIndexRoute =
  AuthMallShippingTemplateIndexRouteImport.update({
    id: '/mall/shipping-template/',
    path: '/mall/shipping-template/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.shipping-template.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthMallProductIndexRoute = AuthMallProductIndexRouteImport.update({
  id: '/mall/product/',
  path: '/mall/product/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.index.lazy').then((d) => d.Route),
)
const AuthMallOrderIndexRoute = AuthMallOrderIndexRouteImport.update({
  id: '/mall/order/',
  path: '/mall/order/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.order.index.lazy').then((d) => d.Route),
)
const AuthMallCouponIndexRoute = AuthMallCouponIndexRouteImport.update({
  id: '/mall/coupon/',
  path: '/mall/coupon/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.coupon.index.lazy').then((d) => d.Route),
)
const AuthMallCollectionIndexRoute = AuthMallCollectionIndexRouteImport.update({
  id: '/mall/collection/',
  path: '/mall/collection/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.collection.index.lazy').then((d) => d.Route),
)
const AuthMallCategoryIndexRoute = AuthMallCategoryIndexRouteImport.update({
  id: '/mall/category/',
  path: '/mall/category/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMallAfterSaleIndexRoute = AuthMallAfterSaleIndexRouteImport.update({
  id: '/mall/after-sale/',
  path: '/mall/after-sale/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.after-sale.index.lazy').then((d) => d.Route),
)
const AuthMallShippingTemplateCreateRoute =
  AuthMallShippingTemplateCreateRouteImport.update({
    id: '/mall/shipping-template/create',
    path: '/mall/shipping-template/create',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.shipping-template.create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthMallProductCreateRoute = AuthMallProductCreateRouteImport.update({
  id: '/mall/product/create',
  path: '/mall/product/create',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.create.lazy').then((d) => d.Route),
)
const AuthMallOrderIdRoute = AuthMallOrderIdRouteImport.update({
  id: '/mall/order/$id',
  path: '/mall/order/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMallCouponCreateRoute = AuthMallCouponCreateRouteImport.update({
  id: '/mall/coupon/create',
  path: '/mall/coupon/create',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.coupon.create.lazy').then((d) => d.Route),
)
const AuthMallCollectionCreateRoute =
  AuthMallCollectionCreateRouteImport.update({
    id: '/mall/collection/create',
    path: '/mall/collection/create',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.collection.create.lazy').then((d) => d.Route),
  )
const AuthMallAfterSaleIdRoute = AuthMallAfterSaleIdRouteImport.update({
  id: '/mall/after-sale/$id',
  path: '/mall/after-sale/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.after-sale.$id.lazy').then((d) => d.Route),
)
const AuthMallShippingTemplateEditIdRoute =
  AuthMallShippingTemplateEditIdRouteImport.update({
    id: '/mall/shipping-template/edit/$id',
    path: '/mall/shipping-template/edit/$id',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.shipping-template.edit.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthMallProductEditIdRoute = AuthMallProductEditIdRouteImport.update({
  id: '/mall/product/edit/$id',
  path: '/mall/product/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.edit.$id.lazy').then((d) => d.Route),
)
const AuthMallCouponEditIdRoute = AuthMallCouponEditIdRouteImport.update({
  id: '/mall/coupon/edit/$id',
  path: '/mall/coupon/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.coupon.edit.$id.lazy').then((d) => d.Route),
)
const AuthMallCollectionEditIdRoute =
  AuthMallCollectionEditIdRouteImport.update({
    id: '/mall/collection/edit/$id',
    path: '/mall/collection/edit/$id',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.collection.edit.$id.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/': typeof AuthIndexRoute
  '/cms/article': typeof AuthCmsArticleRoute
  '/cms/category': typeof AuthCmsCategoryRoute
  '/cms/comment': typeof AuthCmsCommentRoute
  '/cms/resource': typeof AuthCmsResourceRoute
  '/cms/tag': typeof AuthCmsTagRoute
  '/mall/member': typeof AuthMallMemberRoute
  '/system/config': typeof AuthSystemConfigRoute
  '/system/dict': typeof AuthSystemDictRoute
  '/system/log': typeof AuthSystemLogRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/queues': typeof AuthSystemQueuesRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
  '/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/mall/coupon/create': typeof AuthMallCouponCreateRoute
  '/mall/order/$id': typeof AuthMallOrderIdRoute
  '/mall/product/create': typeof AuthMallProductCreateRoute
  '/mall/shipping-template/create': typeof AuthMallShippingTemplateCreateRoute
  '/mall/after-sale': typeof AuthMallAfterSaleIndexRoute
  '/mall/category': typeof AuthMallCategoryIndexRoute
  '/mall/collection': typeof AuthMallCollectionIndexRoute
  '/mall/coupon': typeof AuthMallCouponIndexRoute
  '/mall/order': typeof AuthMallOrderIndexRoute
  '/mall/product': typeof AuthMallProductIndexRoute
  '/mall/shipping-template': typeof AuthMallShippingTemplateIndexRoute
  '/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/mall/coupon/edit/$id': typeof AuthMallCouponEditIdRoute
  '/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
  '/mall/shipping-template/edit/$id': typeof AuthMallShippingTemplateEditIdRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/': typeof AuthIndexRoute
  '/cms/article': typeof AuthCmsArticleRoute
  '/cms/category': typeof AuthCmsCategoryRoute
  '/cms/comment': typeof AuthCmsCommentRoute
  '/cms/resource': typeof AuthCmsResourceRoute
  '/cms/tag': typeof AuthCmsTagRoute
  '/mall/member': typeof AuthMallMemberRoute
  '/system/config': typeof AuthSystemConfigRoute
  '/system/dict': typeof AuthSystemDictRoute
  '/system/log': typeof AuthSystemLogRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/queues': typeof AuthSystemQueuesRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
  '/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/mall/coupon/create': typeof AuthMallCouponCreateRoute
  '/mall/order/$id': typeof AuthMallOrderIdRoute
  '/mall/product/create': typeof AuthMallProductCreateRoute
  '/mall/shipping-template/create': typeof AuthMallShippingTemplateCreateRoute
  '/mall/after-sale': typeof AuthMallAfterSaleIndexRoute
  '/mall/category': typeof AuthMallCategoryIndexRoute
  '/mall/collection': typeof AuthMallCollectionIndexRoute
  '/mall/coupon': typeof AuthMallCouponIndexRoute
  '/mall/order': typeof AuthMallOrderIndexRoute
  '/mall/product': typeof AuthMallProductIndexRoute
  '/mall/shipping-template': typeof AuthMallShippingTemplateIndexRoute
  '/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/mall/coupon/edit/$id': typeof AuthMallCouponEditIdRoute
  '/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
  '/mall/shipping-template/edit/$id': typeof AuthMallShippingTemplateEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/cms/article': typeof AuthCmsArticleRoute
  '/_auth/cms/category': typeof AuthCmsCategoryRoute
  '/_auth/cms/comment': typeof AuthCmsCommentRoute
  '/_auth/cms/resource': typeof AuthCmsResourceRoute
  '/_auth/cms/tag': typeof AuthCmsTagRoute
  '/_auth/mall/member': typeof AuthMallMemberRoute
  '/_auth/system/config': typeof AuthSystemConfigRoute
  '/_auth/system/dict': typeof AuthSystemDictRoute
  '/_auth/system/log': typeof AuthSystemLogRoute
  '/_auth/system/menu': typeof AuthSystemMenuRoute
  '/_auth/system/queues': typeof AuthSystemQueuesRoute
  '/_auth/system/role': typeof AuthSystemRoleRoute
  '/_auth/system/user': typeof AuthSystemUserRoute
  '/_auth/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/_auth/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/_auth/mall/coupon/create': typeof AuthMallCouponCreateRoute
  '/_auth/mall/order/$id': typeof AuthMallOrderIdRoute
  '/_auth/mall/product/create': typeof AuthMallProductCreateRoute
  '/_auth/mall/shipping-template/create': typeof AuthMallShippingTemplateCreateRoute
  '/_auth/mall/after-sale/': typeof AuthMallAfterSaleIndexRoute
  '/_auth/mall/category/': typeof AuthMallCategoryIndexRoute
  '/_auth/mall/collection/': typeof AuthMallCollectionIndexRoute
  '/_auth/mall/coupon/': typeof AuthMallCouponIndexRoute
  '/_auth/mall/order/': typeof AuthMallOrderIndexRoute
  '/_auth/mall/product/': typeof AuthMallProductIndexRoute
  '/_auth/mall/shipping-template/': typeof AuthMallShippingTemplateIndexRoute
  '/_auth/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/_auth/mall/coupon/edit/$id': typeof AuthMallCouponEditIdRoute
  '/_auth/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
  '/_auth/mall/shipping-template/edit/$id': typeof AuthMallShippingTemplateEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/login'
    | '/dashboard'
    | '/'
    | '/cms/article'
    | '/cms/category'
    | '/cms/comment'
    | '/cms/resource'
    | '/cms/tag'
    | '/mall/member'
    | '/system/config'
    | '/system/dict'
    | '/system/log'
    | '/system/menu'
    | '/system/queues'
    | '/system/role'
    | '/system/user'
    | '/mall/after-sale/$id'
    | '/mall/collection/create'
    | '/mall/coupon/create'
    | '/mall/order/$id'
    | '/mall/product/create'
    | '/mall/shipping-template/create'
    | '/mall/after-sale'
    | '/mall/category'
    | '/mall/collection'
    | '/mall/coupon'
    | '/mall/order'
    | '/mall/product'
    | '/mall/shipping-template'
    | '/mall/collection/edit/$id'
    | '/mall/coupon/edit/$id'
    | '/mall/product/edit/$id'
    | '/mall/shipping-template/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/dashboard'
    | '/'
    | '/cms/article'
    | '/cms/category'
    | '/cms/comment'
    | '/cms/resource'
    | '/cms/tag'
    | '/mall/member'
    | '/system/config'
    | '/system/dict'
    | '/system/log'
    | '/system/menu'
    | '/system/queues'
    | '/system/role'
    | '/system/user'
    | '/mall/after-sale/$id'
    | '/mall/collection/create'
    | '/mall/coupon/create'
    | '/mall/order/$id'
    | '/mall/product/create'
    | '/mall/shipping-template/create'
    | '/mall/after-sale'
    | '/mall/category'
    | '/mall/collection'
    | '/mall/coupon'
    | '/mall/order'
    | '/mall/product'
    | '/mall/shipping-template'
    | '/mall/collection/edit/$id'
    | '/mall/coupon/edit/$id'
    | '/mall/product/edit/$id'
    | '/mall/shipping-template/edit/$id'
  id:
    | '__root__'
    | '/403'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/'
    | '/_auth/cms/article'
    | '/_auth/cms/category'
    | '/_auth/cms/comment'
    | '/_auth/cms/resource'
    | '/_auth/cms/tag'
    | '/_auth/mall/member'
    | '/_auth/system/config'
    | '/_auth/system/dict'
    | '/_auth/system/log'
    | '/_auth/system/menu'
    | '/_auth/system/queues'
    | '/_auth/system/role'
    | '/_auth/system/user'
    | '/_auth/mall/after-sale/$id'
    | '/_auth/mall/collection/create'
    | '/_auth/mall/coupon/create'
    | '/_auth/mall/order/$id'
    | '/_auth/mall/product/create'
    | '/_auth/mall/shipping-template/create'
    | '/_auth/mall/after-sale/'
    | '/_auth/mall/category/'
    | '/_auth/mall/collection/'
    | '/_auth/mall/coupon/'
    | '/_auth/mall/order/'
    | '/_auth/mall/product/'
    | '/_auth/mall/shipping-template/'
    | '/_auth/mall/collection/edit/$id'
    | '/_auth/mall/coupon/edit/$id'
    | '/_auth/mall/product/edit/$id'
    | '/_auth/mall/shipping-template/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/user': {
      id: '/_auth/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof AuthSystemUserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/role': {
      id: '/_auth/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthSystemRoleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/queues': {
      id: '/_auth/system/queues'
      path: '/system/queues'
      fullPath: '/system/queues'
      preLoaderRoute: typeof AuthSystemQueuesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/menu': {
      id: '/_auth/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof AuthSystemMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/log': {
      id: '/_auth/system/log'
      path: '/system/log'
      fullPath: '/system/log'
      preLoaderRoute: typeof AuthSystemLogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/dict': {
      id: '/_auth/system/dict'
      path: '/system/dict'
      fullPath: '/system/dict'
      preLoaderRoute: typeof AuthSystemDictRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/config': {
      id: '/_auth/system/config'
      path: '/system/config'
      fullPath: '/system/config'
      preLoaderRoute: typeof AuthSystemConfigRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/member': {
      id: '/_auth/mall/member'
      path: '/mall/member'
      fullPath: '/mall/member'
      preLoaderRoute: typeof AuthMallMemberRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cms/tag': {
      id: '/_auth/cms/tag'
      path: '/cms/tag'
      fullPath: '/cms/tag'
      preLoaderRoute: typeof AuthCmsTagRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cms/resource': {
      id: '/_auth/cms/resource'
      path: '/cms/resource'
      fullPath: '/cms/resource'
      preLoaderRoute: typeof AuthCmsResourceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cms/comment': {
      id: '/_auth/cms/comment'
      path: '/cms/comment'
      fullPath: '/cms/comment'
      preLoaderRoute: typeof AuthCmsCommentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cms/category': {
      id: '/_auth/cms/category'
      path: '/cms/category'
      fullPath: '/cms/category'
      preLoaderRoute: typeof AuthCmsCategoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cms/article': {
      id: '/_auth/cms/article'
      path: '/cms/article'
      fullPath: '/cms/article'
      preLoaderRoute: typeof AuthCmsArticleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/shipping-template/': {
      id: '/_auth/mall/shipping-template/'
      path: '/mall/shipping-template'
      fullPath: '/mall/shipping-template'
      preLoaderRoute: typeof AuthMallShippingTemplateIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/': {
      id: '/_auth/mall/product/'
      path: '/mall/product'
      fullPath: '/mall/product'
      preLoaderRoute: typeof AuthMallProductIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/order/': {
      id: '/_auth/mall/order/'
      path: '/mall/order'
      fullPath: '/mall/order'
      preLoaderRoute: typeof AuthMallOrderIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/coupon/': {
      id: '/_auth/mall/coupon/'
      path: '/mall/coupon'
      fullPath: '/mall/coupon'
      preLoaderRoute: typeof AuthMallCouponIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/': {
      id: '/_auth/mall/collection/'
      path: '/mall/collection'
      fullPath: '/mall/collection'
      preLoaderRoute: typeof AuthMallCollectionIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/category/': {
      id: '/_auth/mall/category/'
      path: '/mall/category'
      fullPath: '/mall/category'
      preLoaderRoute: typeof AuthMallCategoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/after-sale/': {
      id: '/_auth/mall/after-sale/'
      path: '/mall/after-sale'
      fullPath: '/mall/after-sale'
      preLoaderRoute: typeof AuthMallAfterSaleIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/shipping-template/create': {
      id: '/_auth/mall/shipping-template/create'
      path: '/mall/shipping-template/create'
      fullPath: '/mall/shipping-template/create'
      preLoaderRoute: typeof AuthMallShippingTemplateCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/create': {
      id: '/_auth/mall/product/create'
      path: '/mall/product/create'
      fullPath: '/mall/product/create'
      preLoaderRoute: typeof AuthMallProductCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/order/$id': {
      id: '/_auth/mall/order/$id'
      path: '/mall/order/$id'
      fullPath: '/mall/order/$id'
      preLoaderRoute: typeof AuthMallOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/coupon/create': {
      id: '/_auth/mall/coupon/create'
      path: '/mall/coupon/create'
      fullPath: '/mall/coupon/create'
      preLoaderRoute: typeof AuthMallCouponCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/create': {
      id: '/_auth/mall/collection/create'
      path: '/mall/collection/create'
      fullPath: '/mall/collection/create'
      preLoaderRoute: typeof AuthMallCollectionCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/after-sale/$id': {
      id: '/_auth/mall/after-sale/$id'
      path: '/mall/after-sale/$id'
      fullPath: '/mall/after-sale/$id'
      preLoaderRoute: typeof AuthMallAfterSaleIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/shipping-template/edit/$id': {
      id: '/_auth/mall/shipping-template/edit/$id'
      path: '/mall/shipping-template/edit/$id'
      fullPath: '/mall/shipping-template/edit/$id'
      preLoaderRoute: typeof AuthMallShippingTemplateEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/edit/$id': {
      id: '/_auth/mall/product/edit/$id'
      path: '/mall/product/edit/$id'
      fullPath: '/mall/product/edit/$id'
      preLoaderRoute: typeof AuthMallProductEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/coupon/edit/$id': {
      id: '/_auth/mall/coupon/edit/$id'
      path: '/mall/coupon/edit/$id'
      fullPath: '/mall/coupon/edit/$id'
      preLoaderRoute: typeof AuthMallCouponEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/edit/$id': {
      id: '/_auth/mall/collection/edit/$id'
      path: '/mall/collection/edit/$id'
      fullPath: '/mall/collection/edit/$id'
      preLoaderRoute: typeof AuthMallCollectionEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCmsArticleRoute: typeof AuthCmsArticleRoute
  AuthCmsCategoryRoute: typeof AuthCmsCategoryRoute
  AuthCmsCommentRoute: typeof AuthCmsCommentRoute
  AuthCmsResourceRoute: typeof AuthCmsResourceRoute
  AuthCmsTagRoute: typeof AuthCmsTagRoute
  AuthMallMemberRoute: typeof AuthMallMemberRoute
  AuthSystemConfigRoute: typeof AuthSystemConfigRoute
  AuthSystemDictRoute: typeof AuthSystemDictRoute
  AuthSystemLogRoute: typeof AuthSystemLogRoute
  AuthSystemMenuRoute: typeof AuthSystemMenuRoute
  AuthSystemQueuesRoute: typeof AuthSystemQueuesRoute
  AuthSystemRoleRoute: typeof AuthSystemRoleRoute
  AuthSystemUserRoute: typeof AuthSystemUserRoute
  AuthMallAfterSaleIdRoute: typeof AuthMallAfterSaleIdRoute
  AuthMallCollectionCreateRoute: typeof AuthMallCollectionCreateRoute
  AuthMallCouponCreateRoute: typeof AuthMallCouponCreateRoute
  AuthMallOrderIdRoute: typeof AuthMallOrderIdRoute
  AuthMallProductCreateRoute: typeof AuthMallProductCreateRoute
  AuthMallShippingTemplateCreateRoute: typeof AuthMallShippingTemplateCreateRoute
  AuthMallAfterSaleIndexRoute: typeof AuthMallAfterSaleIndexRoute
  AuthMallCategoryIndexRoute: typeof AuthMallCategoryIndexRoute
  AuthMallCollectionIndexRoute: typeof AuthMallCollectionIndexRoute
  AuthMallCouponIndexRoute: typeof AuthMallCouponIndexRoute
  AuthMallOrderIndexRoute: typeof AuthMallOrderIndexRoute
  AuthMallProductIndexRoute: typeof AuthMallProductIndexRoute
  AuthMallShippingTemplateIndexRoute: typeof AuthMallShippingTemplateIndexRoute
  AuthMallCollectionEditIdRoute: typeof AuthMallCollectionEditIdRoute
  AuthMallCouponEditIdRoute: typeof AuthMallCouponEditIdRoute
  AuthMallProductEditIdRoute: typeof AuthMallProductEditIdRoute
  AuthMallShippingTemplateEditIdRoute: typeof AuthMallShippingTemplateEditIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCmsArticleRoute: AuthCmsArticleRoute,
  AuthCmsCategoryRoute: AuthCmsCategoryRoute,
  AuthCmsCommentRoute: AuthCmsCommentRoute,
  AuthCmsResourceRoute: AuthCmsResourceRoute,
  AuthCmsTagRoute: AuthCmsTagRoute,
  AuthMallMemberRoute: AuthMallMemberRoute,
  AuthSystemConfigRoute: AuthSystemConfigRoute,
  AuthSystemDictRoute: AuthSystemDictRoute,
  AuthSystemLogRoute: AuthSystemLogRoute,
  AuthSystemMenuRoute: AuthSystemMenuRoute,
  AuthSystemQueuesRoute: AuthSystemQueuesRoute,
  AuthSystemRoleRoute: AuthSystemRoleRoute,
  AuthSystemUserRoute: AuthSystemUserRoute,
  AuthMallAfterSaleIdRoute: AuthMallAfterSaleIdRoute,
  AuthMallCollectionCreateRoute: AuthMallCollectionCreateRoute,
  AuthMallCouponCreateRoute: AuthMallCouponCreateRoute,
  AuthMallOrderIdRoute: AuthMallOrderIdRoute,
  AuthMallProductCreateRoute: AuthMallProductCreateRoute,
  AuthMallShippingTemplateCreateRoute: AuthMallShippingTemplateCreateRoute,
  AuthMallAfterSaleIndexRoute: AuthMallAfterSaleIndexRoute,
  AuthMallCategoryIndexRoute: AuthMallCategoryIndexRoute,
  AuthMallCollectionIndexRoute: AuthMallCollectionIndexRoute,
  AuthMallCouponIndexRoute: AuthMallCouponIndexRoute,
  AuthMallOrderIndexRoute: AuthMallOrderIndexRoute,
  AuthMallProductIndexRoute: AuthMallProductIndexRoute,
  AuthMallShippingTemplateIndexRoute: AuthMallShippingTemplateIndexRoute,
  AuthMallCollectionEditIdRoute: AuthMallCollectionEditIdRoute,
  AuthMallCouponEditIdRoute: AuthMallCouponEditIdRoute,
  AuthMallProductEditIdRoute: AuthMallProductEditIdRoute,
  AuthMallShippingTemplateEditIdRoute: AuthMallShippingTemplateEditIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
