/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthSystemUserRouteImport } from './routes/_auth.system.user'
import { Route as AuthSystemRoleRouteImport } from './routes/_auth.system.role'
import { Route as AuthSystemQueuesRouteImport } from './routes/_auth.system.queues'
import { Route as AuthSystemMenuRouteImport } from './routes/_auth.system.menu'
import { Route as AuthSystemLogRouteImport } from './routes/_auth.system.log'
import { Route as AuthSystemDictRouteImport } from './routes/_auth.system.dict'
import { Route as AuthSystemConfigRouteImport } from './routes/_auth.system.config'
import { Route as AuthContentTagRouteImport } from './routes/_auth.content.tag'
import { Route as AuthContentResourceRouteImport } from './routes/_auth.content.resource'
import { Route as AuthContentCommentRouteImport } from './routes/_auth.content.comment'
import { Route as AuthContentCategoryRouteImport } from './routes/_auth.content.category'
import { Route as AuthContentArticleRouteImport } from './routes/_auth.content.article'
import { Route as AuthMallProductIndexRouteImport } from './routes/_auth.mall.product.index'
import { Route as AuthMallOrderIndexRouteImport } from './routes/_auth.mall.order.index'
import { Route as AuthMallCollectionIndexRouteImport } from './routes/_auth.mall.collection.index'
import { Route as AuthMallAfterSaleIndexRouteImport } from './routes/_auth.mall.after-sale.index'
import { Route as AuthMallProductCreateRouteImport } from './routes/_auth.mall.product.create'
import { Route as AuthMallOrderIdRouteImport } from './routes/_auth.mall.order.$id'
import { Route as AuthMallCollectionCreateRouteImport } from './routes/_auth.mall.collection.create'
import { Route as AuthMallAfterSaleIdRouteImport } from './routes/_auth.mall.after-sale.$id'
import { Route as AuthMallProductEditIdRouteImport } from './routes/_auth.mall.product.edit.$id'
import { Route as AuthMallCollectionEditIdRouteImport } from './routes/_auth.mall.collection.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_auth.lazy').then((d) => d.Route))
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemUserRoute = AuthSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.user.lazy').then((d) => d.Route),
)
const AuthSystemRoleRoute = AuthSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.role.lazy').then((d) => d.Route),
)
const AuthSystemQueuesRoute = AuthSystemQueuesRouteImport.update({
  id: '/system/queues',
  path: '/system/queues',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemMenuRoute = AuthSystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.menu.lazy').then((d) => d.Route),
)
const AuthSystemLogRoute = AuthSystemLogRouteImport.update({
  id: '/system/log',
  path: '/system/log',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.log.lazy').then((d) => d.Route),
)
const AuthSystemDictRoute = AuthSystemDictRouteImport.update({
  id: '/system/dict',
  path: '/system/dict',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.dict.lazy').then((d) => d.Route),
)
const AuthSystemConfigRoute = AuthSystemConfigRouteImport.update({
  id: '/system/config',
  path: '/system/config',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.system.config.lazy').then((d) => d.Route),
)
const AuthContentTagRoute = AuthContentTagRouteImport.update({
  id: '/content/tag',
  path: '/content/tag',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.content.tag.lazy').then((d) => d.Route),
)
const AuthContentResourceRoute = AuthContentResourceRouteImport.update({
  id: '/content/resource',
  path: '/content/resource',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.content.resource.lazy').then((d) => d.Route),
)
const AuthContentCommentRoute = AuthContentCommentRouteImport.update({
  id: '/content/comment',
  path: '/content/comment',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.content.comment.lazy').then((d) => d.Route),
)
const AuthContentCategoryRoute = AuthContentCategoryRouteImport.update({
  id: '/content/category',
  path: '/content/category',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.content.category.lazy').then((d) => d.Route),
)
const AuthContentArticleRoute = AuthContentArticleRouteImport.update({
  id: '/content/article',
  path: '/content/article',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.content.article.lazy').then((d) => d.Route),
)
const AuthMallProductIndexRoute = AuthMallProductIndexRouteImport.update({
  id: '/mall/product/',
  path: '/mall/product/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.index.lazy').then((d) => d.Route),
)
const AuthMallOrderIndexRoute = AuthMallOrderIndexRouteImport.update({
  id: '/mall/order/',
  path: '/mall/order/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.order.index.lazy').then((d) => d.Route),
)
const AuthMallCollectionIndexRoute = AuthMallCollectionIndexRouteImport.update({
  id: '/mall/collection/',
  path: '/mall/collection/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.collection.index.lazy').then((d) => d.Route),
)
const AuthMallAfterSaleIndexRoute = AuthMallAfterSaleIndexRouteImport.update({
  id: '/mall/after-sale/',
  path: '/mall/after-sale/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.after-sale.index.lazy').then((d) => d.Route),
)
const AuthMallProductCreateRoute = AuthMallProductCreateRouteImport.update({
  id: '/mall/product/create',
  path: '/mall/product/create',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.create.lazy').then((d) => d.Route),
)
const AuthMallOrderIdRoute = AuthMallOrderIdRouteImport.update({
  id: '/mall/order/$id',
  path: '/mall/order/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMallCollectionCreateRoute =
  AuthMallCollectionCreateRouteImport.update({
    id: '/mall/collection/create',
    path: '/mall/collection/create',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.collection.create.lazy').then((d) => d.Route),
  )
const AuthMallAfterSaleIdRoute = AuthMallAfterSaleIdRouteImport.update({
  id: '/mall/after-sale/$id',
  path: '/mall/after-sale/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.after-sale.$id.lazy').then((d) => d.Route),
)
const AuthMallProductEditIdRoute = AuthMallProductEditIdRouteImport.update({
  id: '/mall/product/edit/$id',
  path: '/mall/product/edit/$id',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.mall.product.edit.$id.lazy').then((d) => d.Route),
)
const AuthMallCollectionEditIdRoute =
  AuthMallCollectionEditIdRouteImport.update({
    id: '/mall/collection/edit/$id',
    path: '/mall/collection/edit/$id',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth.mall.collection.edit.$id.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/content/article': typeof AuthContentArticleRoute
  '/content/category': typeof AuthContentCategoryRoute
  '/content/comment': typeof AuthContentCommentRoute
  '/content/resource': typeof AuthContentResourceRoute
  '/content/tag': typeof AuthContentTagRoute
  '/system/config': typeof AuthSystemConfigRoute
  '/system/dict': typeof AuthSystemDictRoute
  '/system/log': typeof AuthSystemLogRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/queues': typeof AuthSystemQueuesRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
  '/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/mall/order/$id': typeof AuthMallOrderIdRoute
  '/mall/product/create': typeof AuthMallProductCreateRoute
  '/mall/after-sale': typeof AuthMallAfterSaleIndexRoute
  '/mall/collection': typeof AuthMallCollectionIndexRoute
  '/mall/order': typeof AuthMallOrderIndexRoute
  '/mall/product': typeof AuthMallProductIndexRoute
  '/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/content/article': typeof AuthContentArticleRoute
  '/content/category': typeof AuthContentCategoryRoute
  '/content/comment': typeof AuthContentCommentRoute
  '/content/resource': typeof AuthContentResourceRoute
  '/content/tag': typeof AuthContentTagRoute
  '/system/config': typeof AuthSystemConfigRoute
  '/system/dict': typeof AuthSystemDictRoute
  '/system/log': typeof AuthSystemLogRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/queues': typeof AuthSystemQueuesRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
  '/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/mall/order/$id': typeof AuthMallOrderIdRoute
  '/mall/product/create': typeof AuthMallProductCreateRoute
  '/mall/after-sale': typeof AuthMallAfterSaleIndexRoute
  '/mall/collection': typeof AuthMallCollectionIndexRoute
  '/mall/order': typeof AuthMallOrderIndexRoute
  '/mall/product': typeof AuthMallProductIndexRoute
  '/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/content/article': typeof AuthContentArticleRoute
  '/_auth/content/category': typeof AuthContentCategoryRoute
  '/_auth/content/comment': typeof AuthContentCommentRoute
  '/_auth/content/resource': typeof AuthContentResourceRoute
  '/_auth/content/tag': typeof AuthContentTagRoute
  '/_auth/system/config': typeof AuthSystemConfigRoute
  '/_auth/system/dict': typeof AuthSystemDictRoute
  '/_auth/system/log': typeof AuthSystemLogRoute
  '/_auth/system/menu': typeof AuthSystemMenuRoute
  '/_auth/system/queues': typeof AuthSystemQueuesRoute
  '/_auth/system/role': typeof AuthSystemRoleRoute
  '/_auth/system/user': typeof AuthSystemUserRoute
  '/_auth/mall/after-sale/$id': typeof AuthMallAfterSaleIdRoute
  '/_auth/mall/collection/create': typeof AuthMallCollectionCreateRoute
  '/_auth/mall/order/$id': typeof AuthMallOrderIdRoute
  '/_auth/mall/product/create': typeof AuthMallProductCreateRoute
  '/_auth/mall/after-sale/': typeof AuthMallAfterSaleIndexRoute
  '/_auth/mall/collection/': typeof AuthMallCollectionIndexRoute
  '/_auth/mall/order/': typeof AuthMallOrderIndexRoute
  '/_auth/mall/product/': typeof AuthMallProductIndexRoute
  '/_auth/mall/collection/edit/$id': typeof AuthMallCollectionEditIdRoute
  '/_auth/mall/product/edit/$id': typeof AuthMallProductEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/login'
    | '/'
    | '/content/article'
    | '/content/category'
    | '/content/comment'
    | '/content/resource'
    | '/content/tag'
    | '/system/config'
    | '/system/dict'
    | '/system/log'
    | '/system/menu'
    | '/system/queues'
    | '/system/role'
    | '/system/user'
    | '/mall/after-sale/$id'
    | '/mall/collection/create'
    | '/mall/order/$id'
    | '/mall/product/create'
    | '/mall/after-sale'
    | '/mall/collection'
    | '/mall/order'
    | '/mall/product'
    | '/mall/collection/edit/$id'
    | '/mall/product/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/'
    | '/content/article'
    | '/content/category'
    | '/content/comment'
    | '/content/resource'
    | '/content/tag'
    | '/system/config'
    | '/system/dict'
    | '/system/log'
    | '/system/menu'
    | '/system/queues'
    | '/system/role'
    | '/system/user'
    | '/mall/after-sale/$id'
    | '/mall/collection/create'
    | '/mall/order/$id'
    | '/mall/product/create'
    | '/mall/after-sale'
    | '/mall/collection'
    | '/mall/order'
    | '/mall/product'
    | '/mall/collection/edit/$id'
    | '/mall/product/edit/$id'
  id:
    | '__root__'
    | '/403'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/content/article'
    | '/_auth/content/category'
    | '/_auth/content/comment'
    | '/_auth/content/resource'
    | '/_auth/content/tag'
    | '/_auth/system/config'
    | '/_auth/system/dict'
    | '/_auth/system/log'
    | '/_auth/system/menu'
    | '/_auth/system/queues'
    | '/_auth/system/role'
    | '/_auth/system/user'
    | '/_auth/mall/after-sale/$id'
    | '/_auth/mall/collection/create'
    | '/_auth/mall/order/$id'
    | '/_auth/mall/product/create'
    | '/_auth/mall/after-sale/'
    | '/_auth/mall/collection/'
    | '/_auth/mall/order/'
    | '/_auth/mall/product/'
    | '/_auth/mall/collection/edit/$id'
    | '/_auth/mall/product/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/user': {
      id: '/_auth/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof AuthSystemUserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/role': {
      id: '/_auth/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthSystemRoleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/queues': {
      id: '/_auth/system/queues'
      path: '/system/queues'
      fullPath: '/system/queues'
      preLoaderRoute: typeof AuthSystemQueuesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/menu': {
      id: '/_auth/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof AuthSystemMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/log': {
      id: '/_auth/system/log'
      path: '/system/log'
      fullPath: '/system/log'
      preLoaderRoute: typeof AuthSystemLogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/dict': {
      id: '/_auth/system/dict'
      path: '/system/dict'
      fullPath: '/system/dict'
      preLoaderRoute: typeof AuthSystemDictRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/config': {
      id: '/_auth/system/config'
      path: '/system/config'
      fullPath: '/system/config'
      preLoaderRoute: typeof AuthSystemConfigRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content/tag': {
      id: '/_auth/content/tag'
      path: '/content/tag'
      fullPath: '/content/tag'
      preLoaderRoute: typeof AuthContentTagRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content/resource': {
      id: '/_auth/content/resource'
      path: '/content/resource'
      fullPath: '/content/resource'
      preLoaderRoute: typeof AuthContentResourceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content/comment': {
      id: '/_auth/content/comment'
      path: '/content/comment'
      fullPath: '/content/comment'
      preLoaderRoute: typeof AuthContentCommentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content/category': {
      id: '/_auth/content/category'
      path: '/content/category'
      fullPath: '/content/category'
      preLoaderRoute: typeof AuthContentCategoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content/article': {
      id: '/_auth/content/article'
      path: '/content/article'
      fullPath: '/content/article'
      preLoaderRoute: typeof AuthContentArticleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/': {
      id: '/_auth/mall/product/'
      path: '/mall/product'
      fullPath: '/mall/product'
      preLoaderRoute: typeof AuthMallProductIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/order/': {
      id: '/_auth/mall/order/'
      path: '/mall/order'
      fullPath: '/mall/order'
      preLoaderRoute: typeof AuthMallOrderIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/': {
      id: '/_auth/mall/collection/'
      path: '/mall/collection'
      fullPath: '/mall/collection'
      preLoaderRoute: typeof AuthMallCollectionIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/after-sale/': {
      id: '/_auth/mall/after-sale/'
      path: '/mall/after-sale'
      fullPath: '/mall/after-sale'
      preLoaderRoute: typeof AuthMallAfterSaleIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/create': {
      id: '/_auth/mall/product/create'
      path: '/mall/product/create'
      fullPath: '/mall/product/create'
      preLoaderRoute: typeof AuthMallProductCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/order/$id': {
      id: '/_auth/mall/order/$id'
      path: '/mall/order/$id'
      fullPath: '/mall/order/$id'
      preLoaderRoute: typeof AuthMallOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/create': {
      id: '/_auth/mall/collection/create'
      path: '/mall/collection/create'
      fullPath: '/mall/collection/create'
      preLoaderRoute: typeof AuthMallCollectionCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/after-sale/$id': {
      id: '/_auth/mall/after-sale/$id'
      path: '/mall/after-sale/$id'
      fullPath: '/mall/after-sale/$id'
      preLoaderRoute: typeof AuthMallAfterSaleIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/product/edit/$id': {
      id: '/_auth/mall/product/edit/$id'
      path: '/mall/product/edit/$id'
      fullPath: '/mall/product/edit/$id'
      preLoaderRoute: typeof AuthMallProductEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mall/collection/edit/$id': {
      id: '/_auth/mall/collection/edit/$id'
      path: '/mall/collection/edit/$id'
      fullPath: '/mall/collection/edit/$id'
      preLoaderRoute: typeof AuthMallCollectionEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthContentArticleRoute: typeof AuthContentArticleRoute
  AuthContentCategoryRoute: typeof AuthContentCategoryRoute
  AuthContentCommentRoute: typeof AuthContentCommentRoute
  AuthContentResourceRoute: typeof AuthContentResourceRoute
  AuthContentTagRoute: typeof AuthContentTagRoute
  AuthSystemConfigRoute: typeof AuthSystemConfigRoute
  AuthSystemDictRoute: typeof AuthSystemDictRoute
  AuthSystemLogRoute: typeof AuthSystemLogRoute
  AuthSystemMenuRoute: typeof AuthSystemMenuRoute
  AuthSystemQueuesRoute: typeof AuthSystemQueuesRoute
  AuthSystemRoleRoute: typeof AuthSystemRoleRoute
  AuthSystemUserRoute: typeof AuthSystemUserRoute
  AuthMallAfterSaleIdRoute: typeof AuthMallAfterSaleIdRoute
  AuthMallCollectionCreateRoute: typeof AuthMallCollectionCreateRoute
  AuthMallOrderIdRoute: typeof AuthMallOrderIdRoute
  AuthMallProductCreateRoute: typeof AuthMallProductCreateRoute
  AuthMallAfterSaleIndexRoute: typeof AuthMallAfterSaleIndexRoute
  AuthMallCollectionIndexRoute: typeof AuthMallCollectionIndexRoute
  AuthMallOrderIndexRoute: typeof AuthMallOrderIndexRoute
  AuthMallProductIndexRoute: typeof AuthMallProductIndexRoute
  AuthMallCollectionEditIdRoute: typeof AuthMallCollectionEditIdRoute
  AuthMallProductEditIdRoute: typeof AuthMallProductEditIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthContentArticleRoute: AuthContentArticleRoute,
  AuthContentCategoryRoute: AuthContentCategoryRoute,
  AuthContentCommentRoute: AuthContentCommentRoute,
  AuthContentResourceRoute: AuthContentResourceRoute,
  AuthContentTagRoute: AuthContentTagRoute,
  AuthSystemConfigRoute: AuthSystemConfigRoute,
  AuthSystemDictRoute: AuthSystemDictRoute,
  AuthSystemLogRoute: AuthSystemLogRoute,
  AuthSystemMenuRoute: AuthSystemMenuRoute,
  AuthSystemQueuesRoute: AuthSystemQueuesRoute,
  AuthSystemRoleRoute: AuthSystemRoleRoute,
  AuthSystemUserRoute: AuthSystemUserRoute,
  AuthMallAfterSaleIdRoute: AuthMallAfterSaleIdRoute,
  AuthMallCollectionCreateRoute: AuthMallCollectionCreateRoute,
  AuthMallOrderIdRoute: AuthMallOrderIdRoute,
  AuthMallProductCreateRoute: AuthMallProductCreateRoute,
  AuthMallAfterSaleIndexRoute: AuthMallAfterSaleIndexRoute,
  AuthMallCollectionIndexRoute: AuthMallCollectionIndexRoute,
  AuthMallOrderIndexRoute: AuthMallOrderIndexRoute,
  AuthMallProductIndexRoute: AuthMallProductIndexRoute,
  AuthMallCollectionEditIdRoute: AuthMallCollectionEditIdRoute,
  AuthMallProductEditIdRoute: AuthMallProductEditIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
